lstest-with-old-code

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -7,36 +7,10 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Hello world action
+    - name: Sleep and Run
       run: |
-        ls 
-        pwd
-        echo "hi"
-    - uses: hashicorp/setup-terraform@v2
-      with:
-         terraform_version: v1.1.3
-    - name: aws access
-      env: # Set the secret as an input
-           accsess_secret: ${{ secrets.ACCESS_KEY }}
-      run: |
-         ls -al
-         ls
-         pwd
-         echo "is there anything ?"
-    - name: aws secret
-      env: # set secret
-           secret_secret: ${{ secrets.SECRET_KEY }}
-      run: |     
-    - name: export aws cred
-      run: |
-         export AWS_ACCESS_KEY_ID=$accsess_secret
-         export AWS_SECRET_ACCESS_KEY=$secret_secret
-    - name: Doing terraform init
-      run: |
-         ls
-         terraform init
-         terraform version
-        
+        echo "Sleeping for 10"
+        sleep 1s
 
   job2:
     name: Job 2
@@ -44,8 +18,20 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-       - name: Hello world action
-         run: |
-            ls 
-            pwd
-       
+    - name: Dependant is Running
+      run: |
+        ls
+        pwd
+        echo "hellllllloooow"
+        echo "Completed job 2, but triggering failure"
+        exit 1
+
+  job3:
+    name: Job 3
+    needs: job2
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Will never run
+      run: |
+        echo "If you can read this, the experiment failed"
